### ISSUE TITLE
Building fatals when building a larger project

### ISSUE THREAD

**Issue by mvriel** [box-project/box2#64]
When I try to build a phar for phpDocumentor I get the following error:

```
? Generating new stub...
? Compressing...
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): unable to create pipe Too many open files' in phar:///home/mvriel/Copy/Projects/OSS/phpDocumentor/phpDocumentor2/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php:974
Stack trace:
#0 [internal function]: KevinGH\Box\Application->KevinGH\Box\{closure}(2, 'proc_open(): un...', 'phar:///home/mv...', 974, Array)
#1 phar:///home/mvriel/Copy/Projects/OSS/phpDocumentor/phpDocumentor2/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php(974): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///home/mvriel/Copy/Projects/OSS/phpDocumentor/phpDocumentor2/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php(793): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/mvriel/Copy/Projects/OSS/phpDocumentor/phpDocumentor2/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php(754): Symfony\Component\Console\Application in phar:///home/mvriel/Copy/Projects/OSS/phpDocumentor/phpDocumentor2/box.phar/src/vendors/symfony/console/Symfony/Component/Console/Application.php on line 974
```

**Comment by mvriel** [comment]
For the record, this is our configuration file: https://github.com/phpDocumentor/phpDocumentor2/blob/develop/box.json

**Comment by ghost** [comment]
Unfortunately I'm having trouble installing the Composer dependencies for the linked branch.

It keeps timing out on `zetacomponents/document`.

Not sure if it's a problem with GitHub or the setup.

**Comment by mvriel** [comment]
I know that the composer setup for phpDocumentor works (unless something changed in the past one or two weeks), odd that those timeouts occur.

**Comment by ghost** [comment]
Yeah, I can't seem to get it to work.

Could you please give it a try and see if it happens on your end?

If it doesn't, I'll have to find another machine to help get your project to build while I figure out my own problem.

**Comment by mvriel** [comment]
I will try this out as soon as I can

**Comment by mvriel** [comment]
Hi @kherge, I have just made changes to the composer.json that should resolve any issues. Can you try it out with the latest version on the develop branch?

**Comment by ghost** [comment]
Managed to get it installed by using the `--prefer-source` option in Composer, it just took a long time.

I will definitely be giving it a look this weekend and hopefully I can come up with a solution.

I've seen this problem before while building a Symfony-based project, and it has to deal with too many file handles being opened at once. I believe that the `phar` extension itself does not close file handles once it is done with them, resulting in the error message you got.

I have an idea (close the phar and re-open it), but I have to test it to see if it works.

I have a question for you, though: did you intend to also include test suites into your phar?

**Comment by mvriel** [comment]
No, test suites should be excluded. I have tried to exclude them as much as possible but some are hard to do without defining a lot of exclude rules because I cannot filter using wildcards (cannot say `*/tests/*`).

The Symfony Components do not have a separate src and tests folder, and that makes excluding harder

**Comment by ghost** [comment]
I was working on this until Packagist started erroring out.

So far I've found out two things:
1. There is a bug in `herrera-io/php-annotations` that needs to be fixed before annotations will work properly. It has been fixed but `herrera-io/php-box` and `kherge/box` need to be updated. I was working on this until Packagist started 504'ing.
2. The dompdf library may not work (not 100% sure on this) at all inside a phar [since it uses `realpath()`](https://github.com/dompdf/dompdf/blob/master/dompdf_config.inc.php#L21) to generate a path to `require()` files off of. [This bug ticket](https://bugs.php.net/bug.php?id=52769) on PHP has been open for over 3 years with no response. I'm wondering how you managed to get your current phar working.

```
PHP Warning:  require_once(/include/functions.inc.php): failed to open stream: No such file or directory in phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/dompdf/dompdf/dompdf_config.inc.php on line 54
PHP Stack trace:
PHP   1. {main}() /home/kherrera/Testing/php/phpdoc/phpDocumentor.phar:0
PHP   2. require() /home/kherrera/Testing/php/phpdoc/phpDocumentor.phar:10
PHP   3. require_once() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/bin/phpdoc.php:26
PHP   4. require_once() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Application.php:39
```

I did manage to get your phar to build, however, using this configuration file:

``` json
{
    "chmod": "0755",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php"
    ],
    "directories": ["src"],
    "directories-bin": ["data"],
    "files": [
        "vendor/autoload.php",
        "VERSION"
    ],
    "finder": [
        {
            "exclude": [
                "Tests",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "main": "bin/phpdoc.php",
    "output": "phpDocumentor.phar",
    "stub": true
}
```

For the moment, the problem is that all comments (and their annotations) are stripped.

**Comment by mvriel** [comment]
Thank you very much for figuring this out! I really want to use box and this helps immensely.

As for PHAR's and realpath; I have had this issue before and always fixed this by avoiding realpath when I want to find stuff inside the phar; even worse: I use realpath when I want to find stuff outside the PHAR.

I had not noticed yet that DOMPDF uses realpath (new component and not tested yet using phar) so that is going to be an issue. Once I get around to working with DOMPDF and doing tests with it I will probably issue a PR to DOMPDF to remove the realpath calls ;)

Do you have a timetable for fixing the stripping of annotations? I currently use them for serializing and deserializing objects ..

**Comment by ghost** [comment]
I released Box 2.4.3, fixing the issues with annotations. I got the project to build successfully, but the problem with the DOMPDF library is still there, so it didn't run. Try that new Box build with the following configuration file:

``` json
{
    "annotations": {
        "ignore": [
            "Annotation",
            "Attribute",
            "Attributes",
            "Required",
            "SuppressWarnings",
            "TODO",
            "Target",
            "abstract",
            "access",
            "api",
            "author",
            "category",
            "code",
            "codeCoverageIgnore",
            "codeCoverageIgnoreEnd",
            "codeCoverageIgnoreStart",
            "copyright",
            "deprec",
            "deprecated",
            "endcode",
            "example",
            "exception",
            "filesource",
            "final",
            "fixme",
            "global",
            "ignore",
            "ingroup",
            "inheritDoc",
            "inheritdoc",
            "internal",
            "license",
            "link",
            "magic",
            "method",
            "name",
            "override",
            "package",
            "package_version",
            "param",
            "private",
            "property",
            "return",
            "see",
            "since",
            "static",
            "staticVar",
            "staticvar",
            "subpackage",
            "throw",
            "throws",
            "todo",
            "tutorial",
            "usedby",
            "uses",
            "var",
            "version"
        ]
    },
    "chmod": "0755",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php"
    ],
    "directories": ["src"],
    "directories-bin": ["data"],
    "files": [
        "vendor/autoload.php",
        "VERSION"
    ],
    "finder": [
        {
            "name": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "finder-bin": [
        {
            "notName": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "main": "bin/phpdoc.php",
    "output": "phpDocumentor.phar",
    "stub": true
}
```

**Comment by mvriel** [comment]
Hi @kherge-old,

I have tried it out with the new version and the building process goes without a problem, truly awesome.

The only problem I encountered now was that the annotation still seem to be filtered out despite the ignore list in the config..

When running phpDocumentor I get the following error:

```
[Doctrine\Common\Annotations\AnnotationException]                                                                                                                    
  [Semantical Error] The class "JMS\Serializer\Annotation\XmlRoot" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then   
  you need to add @Annotation to the _class_ doc comment of "JMS\Serializer\Annotation\XmlRoot". If it is indeed no annotation, then you need to add @IgnoreAnnotatio  
  n("Serializer\XmlRoot") to the _class_ doc comment of class phpDocumentor\Transformer\Template.     
```

In the develop version I have made changes to prevent the DOMPDF issues that you mentioned.

Thank you very much for your help with this issue

**Comment by ghost** [comment]
Can you provide a link to where I can download the phar you built?

**Comment by mvriel** [comment]
I will generate a new phar and provide it; currently in the middle of a deployment so it can take a while :)

**Comment by mvriel** [comment]
Ok, I have generated a file, you can download it from http://pear.phpdoc.org/phpDocumentor2.phar

**Comment by ghost** [comment]
Sorry, but that link is 404ing for me.

**Comment by mvriel** [comment]
My bad, that should have been http://pear.phpdoc.org/phpDocumentor.phar

**Comment by ghost** [comment]
Okay, I think I see the problem. I might've gotten a little overzealous with the list of annotations to ignore. If an annotation is in the `ignore` list, it will be removed. If it's not in the ignore list, the annotations parser will attempt to preserve it, but also make it smaller.

I'm going to run a few more tests to see if it can just be a simple configuration setting change.

**Comment by mvriel** [comment]
Hey @kherge-old, have you had a chance to run those tests? Sorry if I seem impatient, just looking forward to using this :)

**Comment by ghost** [comment]
No worries, I don't see it as impatience! It's been a while since I've replied.

I forgot (:neutral_face:) the results of the previous test, so I'm cloning everything to run them again. I'll have the results in today, and hopefully good news accompanied by a new release.

**Comment by ghost** [comment]
Okay, with some minor adjustments to the configuration file I got phpDocumentor to start building, but then Twig threw an error:

```
PHP Fatal error:  Class 'Twig_Node_Expression_Test_Null' not found in phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Extension/Core.php on line 308
PHP Stack trace:
PHP   1. {main}() /home/kherrera/Testing/php/phpdoc/phpDocumentor.phar:0
PHP   2. require() /home/kherrera/Testing/php/phpdoc/phpDocumentor.phar:10
PHP   3. phpDocumentor\Application->run() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/bin/phpdoc.php:28
PHP   4. Symfony\Component\Console\Application->run() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Application.php:410
PHP   5. Symfony\Component\Console\Application->doRun() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:121
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:191
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:892
PHP   8. phpDocumentor\Command\Project\RunCommand->execute() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
PHP   9. Symfony\Component\Console\Command\Command->run() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Command/Project/RunCommand.php:270
PHP  10. phpDocumentor\Transformer\Command\Project\TransformCommand->execute() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
PHP  11. phpDocumentor\Console\Output\Output->writeTimedLog() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Transformer/Command/Project/TransformCommand.php:197
PHP  12. call_user_func_array() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Console/Output/Output.php:56
PHP  13. phpDocumentor\Transformer\Transformer->execute() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Console/Output/Output.php:56
PHP  14. phpDocumentor\Plugin\Core\Transformer\Writer\Twig->transform() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Transformer/Transformer.php:178
PHP  15. Twig_Environment->render() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Twig.php:114
PHP  16. Twig_Environment->loadTemplate() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:292
PHP  17. __TwigTemplate_d829c4d0890eeef1f290498d7389d0a2d0a6794acd533ca8b9d377de26337085->__construct() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:345
PHP  18. Twig_Environment->loadTemplate() /tmp/phpdoc-twig-cache/d8/29/c4d0890eeef1f290498d7389d0a2d0a6794acd533ca8b9d377de26337085.php:10
PHP  19. __TwigTemplate_e7bbf0f35a77c2ee9af8de0dce6b5b9ff6265b61b78109cb0da2ec4332186b0e->__construct() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:345
PHP  20. Twig_Environment->loadTemplate() /tmp/phpdoc-twig-cache/e7/bb/f0f35a77c2ee9af8de0dce6b5b9ff6265b61b78109cb0da2ec4332186b0e.php:12
PHP  21. Twig_Environment->compileSource() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:334
PHP  22. Twig_Environment->parse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:559
PHP  23. Twig_Parser->parse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Environment.php:507
PHP  24. Twig_Parser->subparse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Parser.php:95
PHP  25. Twig_TokenParser_Block->parse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Parser.php:187
PHP  26. Twig_Parser->subparse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/TokenParser/Block.php:45
PHP  27. Twig_TokenParser_If->parse() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/Parser.php:187
PHP  28. Twig_ExpressionParser->parseExpression() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/TokenParser/If.php:38
PHP  29. Twig_ExpressionParser->getPrimary() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/ExpressionParser.php:41
PHP  30. Twig_ExpressionParser->parseExpression() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/ExpressionParser.php:78
PHP  31. call_user_func() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/ExpressionParser.php:48
PHP  32. Twig_Extension_Core->parseTestExpression() phar:///home/kherrera/Testing/php/phpdoc/phpDocumentor.phar/vendor/twig/twig/lib/Twig/ExpressionParser.php:48
```

This was using the Box built phpDocumentor.phar file to build against the phpDocumentor repository. Here's the configuration file I used:

``` json
{
    "annotations": {
        "ignore": [
            "SuppressWarnings",
            "TODO",
            "abstract",
            "access",
            "api",
            "author",
            "category",
            "code",
            "codeCoverageIgnore",
            "codeCoverageIgnoreEnd",
            "codeCoverageIgnoreStart",
            "copyright",
            "deprec",
            "deprecated",
            "endcode",
            "example",
            "exception",
            "filesource",
            "final",
            "fixme",
            "global",
            "ignore",
            "ingroup",
            "inheritDoc",
            "inheritdoc",
            "internal",
            "license",
            "link",
            "magic",
            "method",
            "name",
            "override",
            "package",
            "package_version",
            "param",
            "private",
            "property",
            "return",
            "see",
            "since",
            "static",
            "staticVar",
            "staticvar",
            "subpackage",
            "throw",
            "throws",
            "todo",
            "tutorial",
            "usedby",
            "uses",
            "var",
            "version"
        ]
    },
    "chmod": "0755",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php"
    ],
    "directories": ["src"],
    "directories-bin": ["data"],
    "files": [
        "vendor/autoload.php",
        "VERSION"
    ],
    "finder": [
        {
            "name": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "finder-bin": [
        {
            "notName": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "main": "bin/phpdoc.php",
    "output": "phpDocumentor.phar",
    "stub": true
}
```

I used your compile script to build your phar and it didn't have any problem creating the documentation.

What's left for me to do is find out what is causing that error.

**Comment by ghost** [comment]
It looks like a different and seemingly unrelated bug might've been causing it.

I have released Box 2.4.4, and with the above configuration settings, it should work! I managed to get the Box built phar to generate documentation for phpDocumentor. The phar is also about half the size of the original one.

**Comment by mvriel** [comment]
I have just tested it with Box 2.4.4 and receive the same twig error that you describe in https://github.com/kherge-archive/Box/issues/64#issuecomment-36267757 while I do not receive that error when using phpDocumentor's source.

I wonder what is going on that Twig cannot find that file in the phar ..

**Comment by ghost** [comment]
Okay, I figured it out. The configuration settings used to filter out the test files also excluded Twig's expression test classes, which ended up breaking things. This new configuration setting should work just fine now (tested):

``` json
{
    "annotations": {
        "ignore": [
            "SuppressWarnings",
            "TODO",
            "abstract",
            "access",
            "api",
            "author",
            "category",
            "code",
            "codeCoverageIgnore",
            "codeCoverageIgnoreEnd",
            "codeCoverageIgnoreStart",
            "copyright",
            "deprec",
            "deprecated",
            "endcode",
            "example",
            "exception",
            "filesource",
            "final",
            "fixme",
            "global",
            "ignore",
            "ingroup",
            "inheritDoc",
            "inheritdoc",
            "internal",
            "license",
            "link",
            "magic",
            "method",
            "name",
            "override",
            "package",
            "package_version",
            "param",
            "private",
            "property",
            "return",
            "see",
            "since",
            "static",
            "staticVar",
            "staticvar",
            "subpackage",
            "throw",
            "throws",
            "todo",
            "tutorial",
            "usedby",
            "uses",
            "var",
            "version"
        ]
    },
    "chmod": "0755",
    "compactors": [
        "Herrera\\Box\\Compactor\\Php"
    ],
    "directories": [
        "src",
        "vendor/twig/twig/lib/Twig/Node/Expression/Test"
    ],
    "directories-bin": ["data"],
    "files": [
        "vendor/autoload.php",
        "VERSION"
    ],
    "finder": [
        {
            "name": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "finder-bin": [
        {
            "notName": "*.php",
            "exclude": [
                "Test",
                "Tests",
                "test",
                "tests"
            ],
            "in": [
                "vendor/cilex/cilex/src",
                "vendor/cilex/console-service-provider/src",
                "vendor/composer",
                "vendor/doctrine/annotations/lib",
                "vendor/doctrine/lexer/lib",
                "vendor/dompdf/dompdf",
                "vendor/erusev/parsedown",
                "vendor/jms/metadata/src",
                "vendor/jms/parser-lib/src",
                "vendor/jms/serializer/src",
                "vendor/monolog/monolog/src",
                "vendor/nikic/php-parser/lib",
                "vendor/nikic/php-parser/grammar",
                "vendor/phenx/php-font-lib",
                "vendor/phpcollection/phpcollection/src",
                "vendor/phpdocumentor/fileset/src",
                "vendor/phpdocumentor/graphviz/src",
                "vendor/phpdocumentor/reflection/src",
                "vendor/phpdocumentor/reflection-docblock/src",
                "vendor/phpoption/phpoption/src",
                "vendor/pimple/pimple/lib",
                "vendor/psr/log/Psr",
                "vendor/symfony",
                "vendor/twig/twig/lib",
                "vendor/zendframework/",
                "vendor/zetacomponents/base/src",
                "vendor/zetacomponents/document/src"
            ]
        }
    ],
    "main": "bin/phpdoc.php",
    "output": "phpDocumentor.phar",
    "stub": true
}
```

**Comment by mvriel** [comment]
Those last changes have indeed fixed all issues and I can generate, and use, the PHAR file now!
Thank you so much for your assistance with this issue and the effort you took to investigate and solve it

**Comment by ghost** [comment]
Really glad I could help!
