### ISSUE TITLE
Doctrine-style Annotations are removed 

### ISSUE THREAD

**Issue by mvriel** [box-project/box2#85]
When I build a new phar using box 2.4.4 then I JMS serializer starts to complain that an annotation is missing:

```
mvriel@vps2686:~/release$ php phpDocumentor.phar --version
PHP Fatal error:  Uncaught exception 'JMS\Serializer\Exception\RuntimeException' with message 'You must define a type for phpDocumentor\Configuration::$title.' in phar:///home/mvriel/release/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:213
Stack trace:
#0 phar:///home/mvriel/release/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php(227): JMS\Serializer\XmlDeserializationVisitor->visitProperty(Object(JMS\Serializer\Metadata\PropertyMetadata), Object(SimpleXMLElement), Object(JMS\Serializer\DeserializationContext))
#1 phar:///home/mvriel/release/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(114): JMS\Serializer\GraphNavigator->accept(Object(SimpleXMLElement), Array, Object(JMS\Serializer\DeserializationContext))
#2 phar:///home/mvriel/release/phpDocumentor.phar/src/phpDocumentor/Configuration/Loader.php(112): JMS\Serializer\Serializer->deserialize('<?xml version="...', 'phpDocumentor\C...', 'xml')
#3 phar:///home/mvriel/release in phar:///home/mvriel/release/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php on line 213
```

But when I check the code it is there:

```
use JMS\Serializer\Annotation as Serializer;

[...]

    /**
     * @var string The title for the generated documentation.
     * @Serializer\Type("string")
     */
    protected $title = '';
```

This would lead me to the conclusion that the compacting removed the type annotation (at the least).
Is this a bug or a configuration issue that was introduced in newer versions?

**Comment by ghost** [comment]
Have you tried extracting the phar to see if the processed file had its annotation removed?

`box extract phpDocumentor.phar` will create a `phpDocumentor.phar-contents` directory.

**Comment by TomasVotruba** [comment]
I have similar problem. My annotations are removed and is disabled app.

I use magic class methods, that are turned to simple getters/setters.

``` php
/**
 * @method setAutowired(TRUE)
 */
```

When I set ignore 'method' annotation, it wipes it's content anyway.

``` php
/**
 * @method
 */
```

I need to keep it completely the same as in original code. Is this box2 issue?

**Comment by ghost** [comment]
Hey @TomasVotruba, your particular issue is a little different. Box only provides support for Doctrine-styled annotations, which is not what you are using. You'll need to create your own custom compactor for those types of annotations, or disable compacting altogether.

**Comment by TomasVotruba** [comment]
How to disable compacting?

**Comment by mvriel** [comment]
Apologies that it took so long for me to respond but life got in the way :)

Anyway: I have recreated the phar file because I had created a workaround for it to work. the output that I got was:

```
namespace phpDocumentor;

use JMS\Serializer\Annotation as Serializer;
use phpDocumentor\Configuration\Logging;
use phpDocumentor\Configuration\Merger\Annotation as Merger;
use phpDocumentor\Partials\Partial;
use phpDocumentor\Plugin\Plugin;
use phpDocumentor\Transformer\Configuration\Transformations;




class Configuration
{
/**
@Serializer\Type("string")

*/
protected $title = '';
```

So it would seem that the annotation is there (but has no leading asterisk, I don't know if that matters). 

Since the annotation is there I am going to dig deeper to see why this error occurs with the extracted contents

**Comment by mvriel** [comment]
Apparently if I change the DocBlock from 

```
/**
@Serializer\Type("string")

*/
```

to 

```
/**
* @Serializer\Type("string")
*/
```

It does work. I assume that the asterisk in front of the annotation is required by Jms Serializer. 

Is there a way to tell the compacter to skip specific files so that I can just tell it to skip the serializable files?

**Comment by TomasVotruba** [comment]
I've finally used composer solution a bit customized, https://github.com/apigen/apigen/commit/31ba2cf30d7a5d6359f4bdd1b0e5ec21bbaf5609

Related to this issue, this fixed it: https://github.com/apigen/apigen/commit/31ba2cf30d7a5d6359f4bdd1b0e5ec21bbaf5609#diff-8dd307e1c3d75a13797b28772c4248c4R147

**Comment by ghost** [comment]
@mvriel, unfortunately no but there is a workaround you can use:

List the files you want to leave as is using the [`files-bin`](https://github.com/box-project/box2/blob/2.0/src/lib/KevinGH/Box/Command/Build.php#L251) configuration setting. That way the other files can be compacted, but the ones that Serializer couldn't parse will be packaged as is without making any changes to it.

**Comment by mvriel** [comment]
What an excellent suggestion! I reckon that files-bin does nothing other than leaving those files alone or does it do anything else?

**Comment by ghost** [comment]
You are correct, the `files-bin` option treats the listed files as if they were binary (like images, videos, etc). This means that Box won't touch the contents when it is imported into the phar.
